[project]
name = "app"
version = "0.1.0"
description = "Main FastAPI App"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "sqladmin>=0.22.0",
    "sqlalchemy>=2.0.46",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"